version: '2'
services:
  postgres_backup:
    extends:
      file: docker-compose.yml
      service: postgres
    command: backup
    environment:
      - POSTGRES_HOST=postgres
      - LOCAL_USER_ID=${LOCAL_USER_ID}
    entrypoint: /scripts/docker-entrypoint.sh
    volumes:
      - './backups:/backups'
    depends_on:
      - postgres
