version: '2'
services:
  django:
    image: ${HUB_HOST}/${COMPOSE_PROJECT_NAME}/django:${PROJECT_VERSION}
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ..
      dockerfile: ./docker/services/django/Dockerfile
    volumes:
      - '../api:/code'
    ports:
      - '127.0.0.1:8000:8000'
