version: '2'
services:
  django_sshd:
    image: haos616/sshd:latest
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - DOCKER_CONTAINER=${COMPOSE_PROJECT_NAME}_django_1
    ports:
      - '127.0.0.1:22945:22'
    pid: host
    depends_on:
      - django
