FROM nginx:1.11.10

RUN apt-get update \
    && apt-get install --no-install-recommends -y python python-pip \
    && rm -rf /var/lib/apt/lists/* \
    && pip install Jinja2

ADD ./docker/images/nginx /scripts

RUN mkdir /public

ADD ./api/public/static /public/static

ENTRYPOINT ["/scripts/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
